Repository 0xPellNetwork/pelldvs-libs, pull requests merged in 2025-02, with the labels that each got.

#1 refactor(crypto/bls): simplify unnecessary code
  crypto/bls/attestation.go
Labels: good first issue

#3 CI: Create CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#2 chore: rename module from golibs to pelldvs-libs
  .gitignore
  .golangci.yml
  Makefile
  README.md
  crypto/bls/attestation.go
  crypto/crypto.go
  crypto/example_test.go
  crypto/random_test.go
  crypto/tmhash/hash_test.go
  go.mod
  json/decoder_test.go
  json/encoder_test.go
  json/helpers_test.go
  json/structs.go
  json/types.go
  log/bench_test.go
  log/lazy.go
  log/level_test.go
  log/tracing_logger_test.go
  log/writer_test.go
  os/os.go
  service/service.go
Labels: enhancement
